// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeUUC_TlKRGjD8Ws4LZiw98gWZbde2Lkk',
    appId: '1:497194386332:web:4d4d5ac2696129205d3e59',
    messagingSenderId: '497194386332',
    projectId: 'schrodingerchess',
    authDomain: 'schrodingerchess.firebaseapp.com',
    storageBucket: 'schrodingerchess.firebasestorage.app',
    measurementId: 'G-BXV7W9SF2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8q2TIWSzoM-0aQuueF7ws3LObFuj-PWM',
    appId: '1:497194386332:android:ea76df3877af64c25d3e59',
    messagingSenderId: '497194386332',
    projectId: 'schrodingerchess',
    storageBucket: 'schrodingerchess.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVI5SD9qzLhM2hsm2NLTgHQ93kYP4-1wE',
    appId: '1:497194386332:ios:b4a7439405d099805d3e59',
    messagingSenderId: '497194386332',
    projectId: 'schrodingerchess',
    storageBucket: 'schrodingerchess.firebasestorage.app',
    androidClientId: '497194386332-cr1ht3cuclepgo1bs2mf29hcppvdvn0t.apps.googleusercontent.com',
    iosClientId: '497194386332-k89dauu7fs5laalqa37uh5mb6bpuq7o9.apps.googleusercontent.com',
    iosBundleId: 'com.example.schroedingerChess',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVI5SD9qzLhM2hsm2NLTgHQ93kYP4-1wE',
    appId: '1:497194386332:ios:b4a7439405d099805d3e59',
    messagingSenderId: '497194386332',
    projectId: 'schrodingerchess',
    storageBucket: 'schrodingerchess.firebasestorage.app',
    androidClientId: '497194386332-cr1ht3cuclepgo1bs2mf29hcppvdvn0t.apps.googleusercontent.com',
    iosClientId: '497194386332-k89dauu7fs5laalqa37uh5mb6bpuq7o9.apps.googleusercontent.com',
    iosBundleId: 'com.example.schroedingerChess',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeUUC_TlKRGjD8Ws4LZiw98gWZbde2Lkk',
    appId: '1:497194386332:web:1ad68e88a09b85945d3e59',
    messagingSenderId: '497194386332',
    projectId: 'schrodingerchess',
    authDomain: 'schrodingerchess.firebaseapp.com',
    storageBucket: 'schrodingerchess.firebasestorage.app',
    measurementId: 'G-75704FN0NH',
  );
}
